services:
  db:
    build:
      context: images/postgres
      dockerfile: Dockerfile
    container_name: login-system-db
    restart: "no"
    environment:
      - POSTGRES_DB=login_system_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  
  pg:
    build:
      context: images/pgadmin/
      dockerfile: Dockerfile
    container_name: login_system_pg
    restart: "no"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=adminpg
    ports:
      - "8080:80"
    volumes:
      - pg:/var/lib/pg
    depends_on:
      - db

volumes:
  db:
  pg: